[tool.pytest.ini_options]
addopts = "--doctest-glob='*.rst' --ignore=wntrqgis/packages --doctest-modules"
testpaths = ['tests/','docs/','wntrqgis/']
filterwarnings = [
    'ignore: .*pkg_resources',
    'ignore:Use of .. or absolute path in a resource path is not allowed:DeprecationWarning'
]
pythonpath = [
  "."
]
[tool.coverage.report]
omit = ["wntrqgis/packages/*","wntrqgis/packages/*/wntr/*.py","wntrqgis/packages/*/wntr/*/*.py","wntrqgis/packages/*/wntr/*/*/*.py","tests/*.py","build.py","create_qgis_venv.py","conftest.py",]


[tool.ruff]
target-version = "py39"
extend = "ruff_defaults.toml"
exclude = ["wntrqgis/qgis_plugin_tools","wntrqgis/resources"]

[tool.ruff.lint.per-file-ignores]
"conf.py" = ["INP001"]

"tests/**/*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
    "SLF001", # tests can access private functions
]


[tool.ruff.lint]

unfixable = [
    "F401", # unused imports
    "F841", # unused variables
]

[[tool.mypy.overrides]]
module = "wntrqgis.qgis_plugin_tools.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = ["qgis.*", "osgeo.*","wntr.*","geopandas.*","shapely.*"]
ignore_missing_imports = true
