line-length = 120

[format]
docstring-code-format = true
docstring-code-line-length = 80

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # pandas
    "PD",
    # flake8-builtins
    "A",
    # Error Messages
    "EM",
    # Future Annotations
    "FA",
    # pytest
    "PT",
    # Use Pathlib
    "PTH",
    #Pep 8 Naming
    "N",
    #Documentation
    # "D",
    # Ruff rules
    "RUF",
    #Arguments
    "ARG",
    # Booleans
    "FBT001","FBT002",
    # Bandit
    "S",
    # Tryceratops Exception
    "TRY",
    # Private member accessed
    "SLF",
    # Pylint Refactor
    "PLR0124",
]
ignore = ["PD901"]

[lint.per-file-ignores]
"**/scripts/*" = ["INP001", "T201"]
"**/tests/**/*" = ["PLC1901", "PLR2004", "PLR6301", "S", "TID252"]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.isort]
known-first-party = ["gusnet"]

[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
