line-length = 120

[format]
docstring-code-format = true
docstring-code-line-length = 80

[lint]
select = [
    "A",
    "ARG",
    "ASYNC",
    "B",
    "BLE",
    "C400",
    "C401",
    "C402",
    "C403",
    "C404",
    "C405",
    "C406",
    "C408",
    "C409",
    "C410",
    "C411",
    "C413",
    "C414",
    "C415",
    "C416",
    "C417",
    "C418",
    "C419",
    "COM818",
    "DTZ001",
    "DTZ002",
    "DTZ003",
    "DTZ004",
    "DTZ005",
    "DTZ006",
    "DTZ007",
    "DTZ011",
    "DTZ012",
    "E",
    "EM101",
    "EM102",
    "EM103",
    "EXE002",
    "EXE003",
    "EXE004",
    "EXE005",
    "F",
    "FA100",
    "FA102",
    "FBT001",
    "FBT002",
    "FLY002",
    "G001",
    "G002",
    "G003",
    "G004",
    "G010",
    "G101",
    "G201",
    "G202",
    "I",
    "ICN001",
    "ICN002",
    "ICN003",
    "INP001",
    "INT001",
    "INT002",
    "INT003",
    "ISC003",
    "N801",
    "N802",
    "N803",
    "N804",
    "N805",
    "N806",
    "N807",
    "N811",
    "N812",
    "N813",
    "N814",
    "N815",
    "N816",
    "N817",
    "N818",
    "N999",
    "PERF101",
    "PERF102",
    "PERF401",
    "PERF402",
    "PGH005",
    "PIE790",
    "PIE794",
    "PIE796",
    "PIE800",
    "PIE804",
    "PIE807",
    "PIE808",
    "PIE810",
    "PLC0105",
    "PLC0131",
    "PLC0132",
    "PLC0205",
    "PLC0208",
    "PLC0414",
    "PLC3002",
    "PLE0100",
    "PLE0101",
    "PLE0116",
    "PLE0117",
    "PLE0118",
    "PLE0241",
    "PLE0302",
    "PLE0307",
    "PLE0604",
    "PLE0605",
    "PLE1142",
    "PLE1205",
    "PLE1206",
    "PLE1300",
    "PLE1307",
    "PLE1310",
    "PLE1507",
    "PLE1700",
    "PLE2502",
    "PLE2510",
    "PLE2512",
    "PLE2513",
    "PLE2514",
    "PLE2515",
    "PLR0124",
    "PLR0133",
    "PLR0206",
    "PLR0402",
    "PLR1711",
    "PLR1714",
    "PLR1722",
    "PLR2004",
    "PLR5501",
    "PLW0120",
    "PLW0127",
    "PLW0129",
    "PLW0131",
    "PLW0406",
    "PLW0602",
    "PLW0603",
    "PLW0711",
    "PLW1508",
    "PLW1509",
    "PLW1510",
    "PLW2901",
    "PLW3301",
    "PT001",
    "PT002",
    "PT003",
    "PT006",
    "PT007",
    "PT008",
    "PT009",
    "PT010",
    "PT011",
    "PT012",
    "PT013",
    "PT014",
    "PT015",
    "PT016",
    "PT017",
    "PT018",
    "PT019",
    "PT020",
    "PT021",
    "PT022",
    "PT023",
    "PT024",
    "PT025",
    "PT026",
    "PT027",
    "PYI001",
    "PYI002",
    "PYI003",
    "PYI004",
    "PYI005",
    "PYI006",
    "PYI007",
    "PYI008",
    "PYI009",
    "PYI010",
    "PYI011",
    "PYI012",
    "PYI013",
    "PYI014",
    "PYI015",
    "PYI016",
    "PYI017",
    "PYI018",
    "PYI019",
    "PYI020",
    "PYI021",
    "PYI024",
    "PYI025",
    "PYI026",
    "PYI029",
    "PYI030",
    "PYI032",
    "PYI033",
    "PYI034",
    "PYI035",
    "PYI036",
    "PYI041",
    "PYI042",
    "PYI043",
    "PYI044",
    "PYI045",
    "PYI046",
    "PYI047",
    "PYI048",
    "PYI049",
    "PYI050",
    "PYI051",
    "PYI052",
    "PYI053",
    "PYI054",
    "PYI055",
    "PYI056",
    "RET503",
    "RET504",
    "RET505",
    "RET506",
    "RET507",
    "RET508",
    "RSE102",
    "RUF",
    "S101",
    "S102",
    "S103",
    "S104",
    "S105",
    "S106",
    "S107",
    "S108",
    "S110",
    "S112",
    "S113",
    "S301",
    "S302",
    "S303",
    "S304",
    "S305",
    "S306",
    "S307",
    "S308",
    "S310",
    "S311",
    "S312",
    "S313",
    "S314",
    "S315",
    "S316",
    "S317",
    "S318",
    "S319",
    "S320",
    "S321",
    "S323",
    "S324",
    "S501",
    "S506",
    "S508",
    "S509",
    "S601",
    "S602",
    "S604",
    "S605",
    "S606",
    "S607",
    "S608",
    "S609",
    "S612",
    "S701",
    "SLF001",
    "SLOT000",
    "SLOT001",
    "SLOT002",
    "T100",
    "T201",
    "T203",
    "TCH001",
    "TCH002",
    "TCH003",
    "TCH004",
    "TCH005",
    "TD004",
    "TD005",
    "TD006",
    "TD007",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # pandas
    "PD",
]
exclude = []

[lint.per-file-ignores]
"**/scripts/*" = ["INP001", "T201"]
"**/tests/**/*" = ["PLC1901", "PLR2004", "PLR6301", "S", "TID252"]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.isort]
known-first-party = ["wntrqgis"]

[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
