name: Conda

on: [push]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda-tests:
    name: '${{ matrix.python-version }}, ${{ matrix.os }}, ${{matrix.wntr-version}}, ${{matrix.qgis}}'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9","3.10","3.11", "3.12","3.13", "3.14" ]
        wntr-version: ["", "wntr"] # don't test no-wntr then versions
        # can optinally add a test for wntr install by installing dependencies geopandas, networkx
        qgis: ["qgis","conda-forge/label/qgis_ltr::qgis"]
        exclude:
          - python-version: "3.12"
            qgis: "conda-forge/label/qgis_ltr::qgis"
          - os: "macos-latest"
            python-version: "3.11"
            qgis: "conda-forge/label/qgis_ltr::qgis"
          - os: "macos-latest"
            python-version: "3.12"
            qgis: "conda-forge/label/qgis_ltr::qgis"
          - os: "macos-latest"
            python-version: "3.13"
          - os: "macos-latest"
            python-version: "3.14"
          - os: "macos-latest"
            wntr-version: "wntr"

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: 'latest'
          channels: conda-forge, defaults
          channel-priority: true
          auto-activate-base: false
      - name: Install packages
        run: |
          conda install -y pytest ${{ matrix.wntr-version}} ${{ matrix.qgis }}
          pip install pytest-qgis
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Python Path
        run: python -c "import sys; print(sys.path)"
      - name: Run tests (non-Ubuntu), don't test wntr
        if: ${{ matrix.os !='ubuntu-latest' }}
        run: python -m pytest -v -m "not needs_wntr and not needs_pandas"
      - name: Run Tests (Ubuntu), don't test wntr
        if: ${{ matrix.os =='ubuntu-latest' }}
        run: xvfb-run -s '+extension GLX -screen 0 1024x768x24' python -m pytest -v -m "not needs_wntr and not needs_pandas"
      - name: Run tests (non-Ubuntu), test wntr
        if: ${{ matrix.os !='ubuntu-latest' && matrix.wntr-version != ''}}
        run: python -m pytest -v -m "needs_wntr or needs_pandas"
      - name: Run Tests (Ubuntu), test wntr
        if: ${{ matrix.os =='ubuntu-latest' && matrix.wntr-version != ''}}
        run: xvfb-run -s '+extension GLX -screen 0 1024x768x24' python -m pytest -v -m "needs_wntr or needs_pandas"
