name: Conda

on: [push, pull_request]

jobs:
  conda-tests:
    name: Conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        shell: bash -el {0}
        run: |
          conda install -y -c conda-forge qgis wntr pytest pytest-cov geopandas pip
          pip install pytest-qgis
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Run tests
        shell: bash -el {0}
        run: pytest
