name: Conda

on: [push, pull_request]

jobs:
  conda-tests:
    name: Conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      QT_DEBUG_PLUGINS: 1
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-13", "windows-latest"]
        python-version: ["3.9", "3.10","3.11", "3.12"]
    steps:
      - name: apt libxcb on ubuntu
        if: ${{ matrix.os =='ubuntu-latest' }}
        run: apt-get install libxcb-xinerama0
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: 'latest'
          channels: conda-forge
          channel-priority: true
          auto-activate-base: false
      - name: Install packages
        shell: bash -el {0}
        run: |
          conda install -y qgis wntr pytest pytest-cov geopandas pytest-xvfb
          pip install pytest-qgis
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Run tests
        shell: bash -el {0}
        run: pytest
