name: Conda windows

on: [push, pull_request]

jobs:
  conda-tests:
    name: Conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.9", "3.12"]
    steps:
      # - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: 'latest'
          channels: conda-forge
          channel-priority: true
          auto-activate-base: false
      - name: Install packages
        run: |
          conda install -y qgis
          python -c "import qgis"
      - name: Run tests (non-Ubuntu)
        if: ${{ matrix.os !='ubuntu-latest' }}
        run: python -m pytest -v
