name: Conda

on: [push, pull_request]

jobs:
  conda-tests:
    name: Conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-13", "windows-latest"]
        python-version: ["3.9", "3.10","3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: 'latest'
          channels: conda-forge
          channel-priority: true
          auto-activate-base: false
      - name: Install packages
        run: |
          conda install -y qgis wntr pytest geopandas
          pip install pytest-qgis pytest-cov
      - name: Conda info
        run: conda info
      - name: Python Path
        run: python -c "import sys; print(sys.path)"
      - name: Run tests (non-Ubuntu)
        if: ${{ matrix.os !='ubuntu-latest' }}
        run: pytest
      - name: Run Tests (Ubuntu)
        if: ${{ matrix.os =='ubuntu-latest' }}
        run: xvfb-run -s '+extension GLX -screen 0 1024x768x24' python -m pytest -v
