# workflow name
name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the wanted branches
on:
  pull_request:
  push:
    branches: [master, main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux_tests:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Remove unsupported versions and add more versions. Use LTR version in the cov_tests job
        docker_tags: ['ltr','3.38.3', latest]
        os: [ubuntu-latest]
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Pull qgis
        run: docker pull qgis/qgis:${{ matrix.docker_tags }}

      # Runs all tests
      - name: Run tests
        run: >
          docker run --rm --net=host --volume `pwd`:/app -w=/app -e QGIS_PLUGIN_IN_CI=1 qgis/qgis:${{ matrix.docker_tags }} sh -c
          "pip3 install -qr requirements-dev.txt --break-system-packages && xvfb-run -s '+extension GLX -screen 0 1024x768x24'
          pytest -v --cov=wntrqgis --cov-report=xml tests/"

      # Upload coverage report. Will not work if the repo is private
      - name: Upload coverage to Codecov
        if: ${{ matrix.docker_tags == 'latest' && !github.event.repository.private }}
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false # set to true when upload is working
          verbose: false

  windows_choco:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Choco install qgis
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install qgis-ltr --version=3.34.4 -y

      - name: Run tests
        shell: pwsh
        run: |
          $env:PATH="C:\Program Files\QGIS 3.34.4\bin;$env:PATH"
          $env:QGIS_PLUGIN_IN_CI=1
          python-qgis-ltr.bat -m pip install -qr requirements-dev.txt
          python-qgis-ltr.bat -m pytest -v

  windows_tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - run: ./.github/workflows/qgis_deploy_install_upgrade_ltr.ps1
        shell: pwsh

      - name: Run tests
        shell: pwsh
        run: |
          $env:PATH="C:\Program Files\OSGeo4W_v2\bin;$env:PATH"
          $env:QGIS_PLUGIN_IN_CI=1
          python-qgis-ltr.bat -m pip install -qr requirements-dev.txt
          python-qgis-ltr.bat -m pytest -v
